### ISSUE TITLE
Problem about data size

### ISSUE THREAD

**Issue by XrKang** [XinyiYing/SAM#2]
Thanks for your great work!
I find the size of middlebury data in Baidu Dropbox is 704*480. How to resize the data？
Thanks again for your great work! Waiting for you response.

**Comment by XinyiYing** [comment]
Following stereoSR, we downsampled the Middlebury dataset in half both horizontally and vertically. The testsets of Middlebury is the same as PASSRnet. 
Your can download the generated HR image of Middlebury in [https://pan.baidu.com/s/1s1jPh8yXpKBDXQH-XZF7pw](https://pan.baidu.com/s/1s1jPh8yXpKBDXQH-XZF7pw)
code：1113
